# This is a basic workflow that is manually triggered

name: Arduino build workflow

# controls actions to run on pull request or change to main branch
on: [push, pull_request]

# A workflow to validate if arduino code will compile 
jobs:
  lint:
    name: Lint compiling arduino code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
  build:
    name: Test compiling for UNO
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v3
