# This is a basic workflow that is manually triggered

name: Arduino build workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push

# A workflow to validate if arduino code will compile 
jobs:
  build:
    name: Test compiling examples for UNO
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v3
